schemaName: mixture_db

dataSources:
  write_ds:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/write_ds?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  read_ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/read_ds_0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  read_ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/read_ds_1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

rules:
- !ENCRYPT
  tables:
    t_encrypt:
      columns:
        password:
          cipherColumn: password_cipher
          encryptorName: password_encryptor
  encryptors:
    password_encryptor:
      type: AES
      props:
        aes-key-value: 123456abc
 
- !READWRITE_SPLITTING
  dataSources:
    wr_group:
      writeDataSourceName: write_ds
      readDataSourceNames: 
        - read_ds_0
        - read_ds_1
      loadBalancerName: random
  loadBalancers:
    random:
      type: RANDOM
